name: lightweight
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  fluttertoast: ^8.2.2
  email_validator: '^2.1.16'
  flutter:
    sdk: flutter
  http: ^1.1.0
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.2
  intl: ^0.17.0
  table_calendar: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
